excludes = [
  "flake.lock",
  "*.png",
  "*.jpg",
  "*.jpeg",
  ".clang-format",
  ".clangd",
  ".envrc",
  ".gitignore",
]

[formatter.nixfmt-rfc-style]
command = "nixfmt"
excludes = []
includes = ["*.nix"]
options = []

[formatter.clang-format]
command = "clang-format"
excludes = []
includes = ["*.c", "*.cc", "*.cpp", "*.h", "*.hh", "*.hpp", "*.proto"]
options = ["-i"]

[formatter.taplo]
command = "taplo"
excludes = []
includes = ["*.toml"]
options = ["format"]

[formatter.prettier]
command = "prettier"
excludes = []
includes = [
  "*.cjs",
  "*.css",
  "*.html",
  "*.js",
  "*.json",
  "*.json5",
  "*.jsx",
  "*.md",
  "*.mdx",
  "*.mjs",
  "*.scss",
  "*.ts",
  "*.tsx",
  "*.vue",
  "*.yaml",
  "*.yml",
]
options = ["--write"]
